export interface ThemeConfig {
  id: string;
  name: string;
  category: string;
  background: string; // CSS background or linear-gradient
  pageTextColor: string;
  cardBackground?: string;
  buttonBg: string;
  buttonTextColor: string;
  buttonBorder?: string;
  buttonShadow?: string;
  buttonRadius: 'rounded-none' | 'rounded-lg' | 'rounded-2xl' | 'rounded-full';
  fontFamily: 'Inter' | 'Outfit' | 'Space Grotesk' | 'Plus Jakarta Sans' | 'Playfair Display';
  bioColor: string;
  badgeBg: string;
}

export const BUILT_IN_THEMES: ThemeConfig[] = [
  {
    id: 'forest_signature',
    name: 'Forest Signature',
    category: 'Editorial',
    background: '#1e392a',
    pageTextColor: '#ffffff',
    bioColor: '#a7d5be',
    cardBackground: '#264b38',
    buttonBg: '#ffffff',
    buttonTextColor: '#1e392a',
    buttonBorder: 'none',
    buttonShadow: '0 4px 14px rgba(0, 0, 0, 0.15)',
    buttonRadius: 'rounded-full',
    fontFamily: 'Plus Jakarta Sans',
    badgeBg: 'rgba(255, 255, 255, 0.12)',
  },
  {
    id: 'chalk_minimal',
    name: 'Chalk Minimal',
    category: 'Light',
    background: '#f3f3f1',
    pageTextColor: '#191919',
    bioColor: '#6e6e69',
    cardBackground: '#ffffff',
    buttonBg: '#ffffff',
    buttonTextColor: '#191919',
    buttonBorder: '1px solid #e5e5e3',
    buttonShadow: '0 2px 8px rgba(0, 0, 0, 0.04)',
    buttonRadius: 'rounded-2xl',
    fontFamily: 'Plus Jakarta Sans',
    badgeBg: '#e8e8e5',
  },
  {
    id: 'lagos_pulse',
    name: 'Lagos Volt',
    category: 'Vibrant',
    background: 'linear-gradient(145deg, #052e16 0%, #064e3b 60%, #022c22 100%)',
    pageTextColor: '#f0fdf4',
    bioColor: '#86efac',
    buttonBg: '#d2e823',
    buttonTextColor: '#052e16',
    buttonBorder: 'none',
    buttonShadow: '0 6px 20px rgba(210, 232, 35, 0.25)',
    buttonRadius: 'rounded-full',
    fontFamily: 'Plus Jakarta Sans',
    badgeBg: 'rgba(210, 232, 35, 0.15)',
  },
  {
    id: 'sandstone_editorial',
    name: 'Sandstone Editorial',
    category: 'Editorial',
    background: '#faf6f0',
    pageTextColor: '#2b2118',
    bioColor: '#7a6755',
    buttonBg: '#2b2118',
    buttonTextColor: '#faf6f0',
    buttonBorder: 'none',
    buttonShadow: '0 4px 14px rgba(43, 33, 24, 0.12)',
    buttonRadius: 'rounded-none',
    fontFamily: 'Playfair Display',
    badgeBg: '#eee6da',
  },
  {
    id: 'matcha_sage',
    name: 'Matcha Sage',
    category: 'Organic',
    background: '#e9efe8',
    pageTextColor: '#1e3024',
    bioColor: '#587361',
    buttonBg: '#1e392a',
    buttonTextColor: '#ffffff',
    buttonBorder: 'none',
    buttonShadow: '0 4px 12px rgba(30, 57, 42, 0.12)',
    buttonRadius: 'rounded-2xl',
    fontFamily: 'Inter',
    badgeBg: '#d9e3d7',
  },
  {
    id: 'onyx_noir',
    name: 'Onyx Noir',
    category: 'Dark',
    background: '#121214',
    pageTextColor: '#ffffff',
    bioColor: '#a1a1aa',
    cardBackground: '#18181b',
    buttonBg: '#222225',
    buttonTextColor: '#ffffff',
    buttonBorder: '1px solid rgba(255, 255, 255, 0.08)',
    buttonShadow: '0 4px 14px rgba(0, 0, 0, 0.35)',
    buttonRadius: 'rounded-2xl',
    fontFamily: 'Inter',
    badgeBg: 'rgba(255, 255, 255, 0.06)',
  },
  {
    id: 'warm_terracotta',
    name: 'Sunset Terracotta',
    category: 'Warm',
    background: '#fef7ee',
    pageTextColor: '#431407',
    bioColor: '#9a3412',
    buttonBg: '#ea580c',
    buttonTextColor: '#ffffff',
    buttonBorder: 'none',
    buttonShadow: '0 4px 14px rgba(234, 88, 12, 0.2)',
    buttonRadius: 'rounded-full',
    fontFamily: 'Outfit',
    badgeBg: '#ffedd5',
  },
  {
    id: 'retro_pop',
    name: 'Neo Brutalist Pop',
    category: 'Creative',
    background: '#fef3c7',
    pageTextColor: '#000000',
    bioColor: '#451a03',
    buttonBg: '#ffffff',
    buttonTextColor: '#000000',
    buttonBorder: '2px solid #000000',
    buttonShadow: '4px 4px 0px #000000',
    buttonRadius: 'rounded-lg',
    fontFamily: 'Space Grotesk',
    badgeBg: '#fde68a',
  },
  {
    id: 'cyber_night',
    name: 'Midnight Electric',
    category: 'Dark',
    background: '#0a0f1d',
    pageTextColor: '#ffffff',
    bioColor: '#818cf8',
    buttonBg: '#4f46e5',
    buttonTextColor: '#ffffff',
    buttonBorder: 'none',
    buttonShadow: '0 6px 20px rgba(79, 70, 229, 0.35)',
    buttonRadius: 'rounded-2xl',
    fontFamily: 'Outfit',
    badgeBg: 'rgba(79, 70, 229, 0.15)',
  },
];

export const DEFAULT_THEME = BUILT_IN_THEMES[0];

